[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

# ✅ Force Netlify to always rebuild cleanly (no cache)
[build.environment]
  NETLIFY_USE_YARN = "false"
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  CI = "true"

# 🧹 Prevent serving stale cache
[context.production.environment]
  NETLIFY_NEXT_PLUGIN_SKIP_CACHE = "true"
  NEXT_FORCE_CLEAN_BUILD = "true"

# 🚀 Redirects — ensure clean Next.js routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 💡 Optional: add security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"