name: Daily Product Intelligence Cron

on:
  schedule:
    - cron: '0 9 * * *'   # runs daily at 09:00 UTC
  workflow_dispatch:

jobs:
  run-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Product Intelligence cron endpoint
        env:
          PROD_URL: ${{ secrets.PROD_URL }}
        run: |
          echo "Calling ${PROD_URL}/api/cron ..."
          curl -s -o /dev/null -w "%{http_code}" "${PROD_URL}/api/cron" || true
